services:
  gocron_api:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: gocron_api
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Bangkok
      - GOCRON_API=true